// Package wireagent is the conversational agent for Google Wire-generated
// dependency-injection code. Its job is to keep wire_gen.go files
// consistent with their wire.go injector declarations.
//
// One agent handles all wire-using packages in the module — a single
// Claude conversation has the full picture rather than N parallel ones.
// The agent's role makes this explicit ("you may have multiple wire
// packages; reason across them as a whole").
package wireagent

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/vinodhalaharvi/coven/agent"
	"github.com/vinodhalaharvi/coven/algebra/blackboard"
	"github.com/vinodhalaharvi/coven/fsmonitor"
	"github.com/vinodhalaharvi/coven/llm"
	"github.com/vinodhalaharvi/coven/registry"
)

// Role is the system prompt that primes Claude on this agent's job.
const Role = `You are the wire agent for a Go project. Your single job is to keep generated dependency-injection code (wire_gen.go) consistent with their hand-written wire.go injector declarations.

A wire-using package contains:
  - wire.go: a file with the '//go:build wireinject' or '// +build wireinject' build constraint, declaring injector functions that call wire.Build(...) with provider sets. This file is hand-written; you do NOT edit it.
  - wire_gen.go: machine-generated by the 'wire' tool. You DO regenerate this when wire.go changes.

A project may have ZERO, ONE, or MANY wire-using packages. You handle all of them.

Your method, in order:
  1. When you wake, find every wire-using package by globbing for files with the wireinject build constraint. If none exist, the project has no wire domain — say so and stop.
  2. For each wire-using package, check whether wire_gen.go exists and is current relative to wire.go. If wire_gen.go is missing, stale, or wire.go was just edited, regenerate.
  3. The regeneration command is 'wire ./<package-path-relative-to-module-root>'. The 'wire' binary should already be on PATH; if it's not, propose 'go install github.com/google/wire/cmd/wire@latest'.
  4. After regeneration, verify wire_gen.go was written. If 'wire' fails, read its output, diagnose:
       - missing import 'github.com/google/wire' in go.mod → propose 'go get github.com/google/wire'
       - 'no injector functions in package' → wire.go declares a ProviderSet but no injector function. This is a human design decision; explain plainly and stop.
       - other errors → explain to the user, don't try to fix code automatically.

Constraints:
  - You do NOT edit wire.go yourself. Injector design is a human decision.
  - You do NOT touch *.pb.go (proto agent's domain) or sqlc-generated files (sqlc agent's domain).
  - You do NOT alter go.mod beyond what is required to add the wire runtime.
  - When you've reached a consistent state, return one short final message describing what you did.`

// Config configures a wireagent.
type Config struct {
	ID         string
	ModuleRoot string
	Sender     llm.Sender
	FSBoard    *blackboard.Board[fsmonitor.FileChangeFact]
	Confirm    agent.ConfirmFunc
	Print      agent.PrintFunc
	Settle     time.Duration // wait this long after a burst before waking; default 1s
}

// Agent is the long-running wire agent.
type Agent struct {
	cfg   Config
	inner *agent.Agent

	mu      sync.Mutex
	pending bool
	last    time.Time
}

// New constructs a wireagent.
func New(cfg Config) *Agent {
	if cfg.ID == "" {
		cfg.ID = "wire-agent"
	}
	if cfg.Settle <= 0 {
		cfg.Settle = 1 * time.Second
	}
	inner := agent.New(agent.Config{
		ID:      cfg.ID,
		Role:    Role,
		Tools:   agent.StandardTools(cfg.ModuleRoot),
		Sender:  cfg.Sender,
		Confirm: cfg.Confirm,
		Print:   cfg.Print,
	})
	return &Agent{cfg: cfg, inner: inner}
}

// IsRelevant reports whether a file path is in the wire agent's domain.
//
// Wire-relevant paths:
//   - any file named wire.go or wire_gen.go
//   - go.mod (since the wire runtime dep lives there and an edit may
//     unblock previously-failing wire runs)
func IsRelevant(path string) bool {
	base := filepath.Base(path)
	if base == "wire.go" || base == "wire_gen.go" {
		return true
	}
	if base == "go.mod" {
		return true
	}
	return false
}

// Run starts the agent's subscription loop. Blocks until ctx is cancelled.
func (a *Agent) Run(ctx context.Context) error {
	go a.wakeOnce(ctx, "startup: just attached. Survey the project for wire-using packages and bring the wire domain to a healthy state.")

	if a.cfg.FSBoard == nil {
		<-ctx.Done()
		return nil
	}

	sub := fsmonitor.Subscribe(a.cfg.FSBoard, func(f fsmonitor.FileChangeFact) bool {
		for _, p := range f.ChangedFiles {
			if IsRelevant(p) {
				return true
			}
		}
		return false
	})
	ch, err := sub(ctx)
	if err != nil {
		return err
	}

	var pendingFiles []string
	var timer *time.Timer
	resetTimer := func() {
		if timer != nil {
			timer.Stop()
		}
		timer = time.AfterFunc(a.cfg.Settle, func() {
			files := pendingFiles
			pendingFiles = nil
			obs := formatObservation(files)
			a.wakeOnce(ctx, obs)
		})
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case f, ok := <-ch:
			if !ok {
				return nil
			}
			for _, p := range f.ChangedFiles {
				if IsRelevant(p) {
					pendingFiles = append(pendingFiles, p)
				}
			}
			resetTimer()
		}
	}
}

func (a *Agent) wakeOnce(ctx context.Context, observation string) {
	a.mu.Lock()
	if a.pending {
		a.mu.Unlock()
		return
	}
	a.pending = true
	a.last = time.Now()
	a.mu.Unlock()

	defer func() {
		a.mu.Lock()
		a.pending = false
		a.mu.Unlock()
	}()

	a.cfg.Print(fmt.Sprintf("\n  [%s] waking: %s\n", a.cfg.ID, truncate(observation, 80)))
	_, err := a.inner.Wake(ctx, observation)
	if err != nil {
		a.cfg.Print(fmt.Sprintf("  [%s] error: %v\n", a.cfg.ID, err))
	}
}

// HistoryLen exposes the inner agent's history length for tests.
func (a *Agent) HistoryLen() int { return a.inner.HistoryLen() }

func formatObservation(files []string) string {
	if len(files) == 0 {
		return "filesystem activity in your domain (no specific files identified)."
	}
	seen := make(map[string]bool)
	uniq := make([]string, 0, len(files))
	for _, f := range files {
		if !seen[f] {
			seen[f] = true
			uniq = append(uniq, f)
		}
	}
	if len(uniq) == 1 {
		return "observed change to: " + uniq[0]
	}
	return fmt.Sprintf("observed changes to %d files in your domain:\n  %s", len(uniq), strings.Join(uniq, "\n  "))
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// init registers wire-agent with the v2 router. v1 cmd/demo wires this
// up via -conv-wire directly; this registration is for v2 router metadata.
func init() {
	registry.Register(registry.AgentSpec{
		Name:        "wire",
		Description: "regenerate wire DI injectors when providers or wire.go changes",
		Role:        Role,
		TypicalTriggers: "Changes to wire.go (provider declarations) or new constructors / interfaces in packages that wire.go imports.",
		DomainFiles:     "wire_gen.go (and only wire_gen.go — wire.go itself is human-authored).",
		AvoidsWhen:      "Skip if wire.go doesn't exist in the project. Skip changes purely in test files or generated code that doesn't affect provider signatures.",
		ExampleScenarios: "When app/services.go adds a new constructor NewBillingService, and app/wire.go is updated to include wire.NewSet(..., NewBillingService), this agent runs wire ./app/... to regenerate wire_gen.go with the new initializer.",
		Detect: func(goMod string, moduleRoot string) bool {
			return registry.HasDep(goMod, "github.com/google/wire")
		},
		Build: func(deps registry.BuildDeps) registry.Runner {
			return New(Config{
				ID:         "wire-agent",
				ModuleRoot: deps.ModuleRoot,
				Sender:     deps.Sender,
				FSBoard:    deps.FSBoard,
				Confirm:    deps.Confirm,
				Print:      deps.Print,
				Settle:     1 * time.Second,
			})
		},
	})
}
