package sqlcagent

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/vinodhalaharvi/coven/algebra/blackboard"
	"github.com/vinodhalaharvi/coven/codegen"
	"github.com/vinodhalaharvi/coven/freeap"
	"github.com/vinodhalaharvi/coven/ownership"
)

func TestHasSqlcConfig(t *testing.T) {
	dir := t.TempDir()
	if HasSqlcConfig(dir) {
		t.Error("empty dir should not have sqlc config")
	}
	for _, name := range []string{"sqlc.yaml", "sqlc.yml", "sqlc.json"} {
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, name), []byte("version: \"2\"\n"), 0644)
		if !HasSqlcConfig(dir) {
			t.Errorf("%s should be detected", name)
		}
	}
}

func TestProject_HealthyAndUnhealthy(t *testing.T) {
	p := Project("sqlc-test")
	f := p(Cfg{GenRoot: "/x/gen"}, codegen.RunResult{Output: "ok"}, []string{"/x/gen/db.go"}, nil)
	if !f.OK || f.AgentID != "sqlc-test" || f.GenRoot != "/x/gen" {
		t.Errorf("healthy projection wrong: %+v", f)
	}
	f2 := p(Cfg{GenRoot: "/x/gen"}, codegen.RunResult{Output: "boom"}, nil, errAny("boom"))
	if f2.OK {
		t.Error("unhealthy projection should be OK=false")
	}
}

type errAny string

func (e errAny) Error() string { return string(e) }

// fakeRunner pretends to be sqlc — emits a deterministic Go file.
func fakeRunner(genRoot string, content []byte) codegen.Runner[Cfg] {
	return func(ctx context.Context, cfg Cfg) (codegen.RunResult, error) {
		path := filepath.Join(genRoot, "queries.sql.go")
		return codegen.RunResult{
			Files:  []codegen.GeneratedFile{{Path: path, Bytes: content}},
			Output: "ok",
		}, nil
	}
}

func TestAgent_FakeRunner_WritesGenFile(t *testing.T) {
	moduleRoot := t.TempDir()
	genRoot := filepath.Join(moduleRoot, "internal", "db")
	if err := os.MkdirAll(genRoot, 0755); err != nil {
		t.Fatal(err)
	}

	board := blackboard.New[Fact](blackboard.Config{})
	reg := ownership.New()

	cfg := codegen.Config[Cfg, Fact]{
		AgentID:  "sqlc-test",
		Cfg:      Cfg{ModuleRoot: moduleRoot, GenRoot: genRoot},
		Runner:   fakeRunner(genRoot, []byte("// generated by sqlc\npackage db\n")),
		Project:  Project("sqlc-test"),
		Board:    board,
		BoardKey: func(f Fact) string { return Key(f.GenRoot) },
		Owner:    reg,
	}

	w := codegen.BuildReactiveWorker(cfg)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	fact, err := freeap.Run(ctx, w.Handle(codegen.Trigger{}))
	if err != nil {
		t.Fatal(err)
	}

	gen := filepath.Join(genRoot, "queries.sql.go")
	body, err := os.ReadFile(gen)
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "// generated by sqlc\npackage db\n" {
		t.Errorf("body = %q", body)
	}
	if !fact.OK {
		t.Error("fact should be OK")
	}
	if owner, owned := reg.Owner(gen); !owned || owner != "sqlc-test" {
		t.Errorf("ownership = %q,%v", owner, owned)
	}
}

func TestAgent_DiffWriteSkipsUnchanged(t *testing.T) {
	moduleRoot := t.TempDir()
	genRoot := filepath.Join(moduleRoot, "gen")
	if err := os.MkdirAll(genRoot, 0755); err != nil {
		t.Fatal(err)
	}
	body := []byte("// stable content\npackage db\n")
	os.WriteFile(filepath.Join(genRoot, "queries.sql.go"), body, 0644)

	cfg := codegen.Config[Cfg, Fact]{
		AgentID:  "sqlc-test",
		Cfg:      Cfg{ModuleRoot: moduleRoot, GenRoot: genRoot},
		Runner:   fakeRunner(genRoot, body),
		Project:  Project("sqlc-test"),
		BoardKey: func(f Fact) string { return Key(f.GenRoot) },
	}
	w := codegen.BuildReactiveWorker(cfg)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	fact, err := freeap.Run(ctx, w.Handle(codegen.Trigger{}))
	if err != nil {
		t.Fatal(err)
	}
	if len(fact.ChangedFiles) != 0 {
		t.Errorf("expected 0 changed files, got %v", fact.ChangedFiles)
	}
}
