// Package testagent is the conversational agent that keeps Go tests
// healthy. When .go files change, it wakes and hands the situation to
// Claude — Claude reads the project, decides what tests are missing
// or stale, writes test files with real assertions, runs go test,
// reports.
//
// The agent itself is pure plumbing: subscribe to fsmonitor, debounce,
// wake. All decisions about what to test, what assertions to write,
// and when work is needed live in Claude's head, guided by the role
// string and the project's actual state.
//
// Equilibrium: every public function in scope has at least a sensible
// test, AND `go test ./...` passes.
package testagent

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/vinodhalaharvi/coven/agent"
	"github.com/vinodhalaharvi/coven/algebra/blackboard"
	"github.com/vinodhalaharvi/coven/fsmonitor"
	"github.com/vinodhalaharvi/coven/llm"
	"github.com/vinodhalaharvi/coven/registry"
)

const Role = `You are the test agent. Your job is to keep tests healthy: every public function in the project's scope has at least one sensible test, AND ` + "`go test ./...`" + ` passes.

You wake on any .go file change. Decide whether work is needed. If yes, propose it. If no, return a short "nothing to do" message and reach equilibrium.

Method:
  1. Survey efficiently. Use ` + "`pureast`" + ` to enumerate symbols rather than reading whole files. For example:
     - ` + "`pureast(op=list_symbols, path=internal/service)`" + ` to see what's in a package
     - ` + "`pureast(op=list_symbols, path=., kind=function)`" + ` to find functions across the project
     - ` + "`pureast(op=search, pattern=Test)`" + ` to find existing tests
     - ` + "`pureast(op=methods, symbol=OrderService)`" + ` to enumerate methods on a type
     Only read_file the SPECIFIC function bodies you need to understand for writing assertions, not whole files. This keeps your context window manageable on large projects.
  2. Read existing _test.go files (or pureast on them) to learn the project's test style — table tests vs simple unit tests, testify vs plain testing, naming conventions, helper patterns. Match the existing style; don't impose a new one.
  3. For functions without tests: write actual test files with real assertions. Read the function body to understand what it does, then write tests that reflect that behavior. If the function clearly returns sorted output, assert sorted. If it errors on nil, test that. If it has obvious edge cases (empty input, zero values), include them.
  4. For each test file you propose, run via exec heredoc (auditable diff, individual y/n).
  5. After writes, run ` + "`go test ./...`" + ` to verify your tests are syntactically correct and compile. If a test you wrote fails because of a wrong assertion, propose a fix to the assertion. If a test fails because the implementation is buggy, report that — do NOT modify the implementation; that's the user's job.
  6. Reach equilibrium when public functions have tests AND go test passes.

Constraints:
  - You write ONLY *_test.go files. You do NOT modify production code, ever.
  - You do NOT add deps to go.mod. If a project uses testify and you want to use it, fine (it's already a dep). Don't introduce new test frameworks.
  - You DO write real assertions, not TODO stubs. The user reviews your assertions via y/n; if you got something wrong, they decline. That's the contract. Stub-with-TODO is less useful than real-but-imperfect.
  - Don't try to fix failing implementation code. If your test reveals a bug in the function under test, say so and stop. The user decides what to do.
  - Don't write tests for tests, internal helpers, or main(). Focus on exported functions and methods on exported types.
  - Skip functions where you genuinely can't tell what to assert (e.g. impure side effects, complex async behavior). Say "I don't know what this should assert" and move on.

Scope:
  - Public functions in non-vendor, non-generated packages.
  - Methods on exported types.
  - Skip files in gen/, generated by sqlc/wire/buf/etc. — those are handled by their own agents and aren't typically test-worthy at this layer.

If the project's tests are already comprehensive and pass, say so and stop. Equilibrium reached trivially.

When you've added tests for what was missing and go test passes, summarize and stop. You'll wake again on the next .go file change.`

type Config struct {
	ID         string
	ModuleRoot string
	Sender     llm.Sender
	FSBoard    *blackboard.Board[fsmonitor.FileChangeFact]
	Confirm    agent.ConfirmFunc
	Print      agent.PrintFunc
	Settle     time.Duration
}

type Agent struct {
	cfg     Config
	inner   *agent.Agent
	mu      sync.Mutex
	pending bool
}

func New(cfg Config) *Agent {
	if cfg.ID == "" {
		cfg.ID = "test-agent"
	}
	if cfg.Settle <= 0 {
		// Long settle: test-agent is cross-cutting and should wake AFTER
		// editing has stopped, not on every save. 5s is conservative;
		// tunable.
		cfg.Settle = 5 * time.Second
	}
	inner := agent.New(agent.Config{
		ID:       cfg.ID,
		Role:     Role,
		Tools:    agent.StandardTools(cfg.ModuleRoot),
		Sender:   cfg.Sender,
		Confirm:  cfg.Confirm,
		Print:    cfg.Print,
		MaxTurns: 80, // Test scaffolding can take many tool calls on a large project.
	})
	return &Agent{cfg: cfg, inner: inner}
}

// IsRelevant: any .go file change. The agent doesn't pre-filter by
// "is this a test file" or "is this in a particular directory" —
// Claude decides what's worth testing based on what changed.
func IsRelevant(path string) bool {
	return strings.HasSuffix(path, ".go")
}

func (a *Agent) Run(ctx context.Context) error {
	go a.wakeOnce(ctx, "startup: just attached. Survey the project for public functions that lack tests, identify drift between existing tests and the code they cover, and bring the test domain to a healthy state. If everything is already tested and go test passes, say so and stop.")

	if a.cfg.FSBoard == nil {
		<-ctx.Done()
		return nil
	}

	sub := fsmonitor.Subscribe(a.cfg.FSBoard, func(f fsmonitor.FileChangeFact) bool {
		for _, p := range f.ChangedFiles {
			if IsRelevant(p) {
				return true
			}
		}
		return false
	})
	ch, err := sub(ctx)
	if err != nil {
		return err
	}

	var pendingFiles []string
	var timer *time.Timer
	resetTimer := func() {
		if timer != nil {
			timer.Stop()
		}
		timer = time.AfterFunc(a.cfg.Settle, func() {
			files := pendingFiles
			pendingFiles = nil
			a.wakeOnce(ctx, formatObservation(files))
		})
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case f, ok := <-ch:
			if !ok {
				return nil
			}
			for _, p := range f.ChangedFiles {
				if IsRelevant(p) {
					pendingFiles = append(pendingFiles, p)
				}
			}
			resetTimer()
		}
	}
}

func (a *Agent) wakeOnce(ctx context.Context, observation string) {
	a.mu.Lock()
	if a.pending {
		a.mu.Unlock()
		return
	}
	a.pending = true
	a.mu.Unlock()
	defer func() {
		a.mu.Lock()
		a.pending = false
		a.mu.Unlock()
	}()

	a.cfg.Print(fmt.Sprintf("\n  [%s] waking: %s\n", a.cfg.ID, truncate(observation, 80)))
	if _, err := a.inner.Wake(ctx, observation); err != nil {
		a.cfg.Print(fmt.Sprintf("  [%s] error: %v\n", a.cfg.ID, err))
	}
}

func (a *Agent) HistoryLen() int { return a.inner.HistoryLen() }

func formatObservation(files []string) string {
	if len(files) == 0 {
		return "filesystem activity in your domain (no specific files identified)."
	}
	seen := map[string]bool{}
	uniq := make([]string, 0, len(files))
	for _, f := range files {
		if !seen[f] {
			seen[f] = true
			uniq = append(uniq, f)
		}
	}
	const maxShown = 10
	if len(uniq) <= maxShown {
		if len(uniq) == 1 {
			return "observed change to: " + uniq[0]
		}
		return fmt.Sprintf("observed changes to %d files:\n  %s", len(uniq), strings.Join(uniq, "\n  "))
	}
	shown := uniq[:maxShown]
	rest := len(uniq) - maxShown
	return fmt.Sprintf("observed changes to %d files (showing first %d):\n  %s\n  ... and %d more", len(uniq), maxShown, strings.Join(shown, "\n  "), rest)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// init registers this agent. Detector: always relevant — any Go project
// can benefit from test coverage maintenance. Role string handles the
// "everything's already tested, nothing to do" case cleanly.
func init() {
	registry.Register(registry.AgentSpec{
		Name:        "test",
		Description: "scaffold tests for public functions and verify go test passes",
		Role:        Role,
		TypicalTriggers: "New public functions added without corresponding tests, or existing test files referencing changed function signatures.",
		DomainFiles:     "*_test.go files anywhere in the project.",
		AvoidsWhen:      "Skip if all public functions already have tests AND go test passes. Skip changes that are purely cosmetic (whitespace, comments) or limited to generated code in gen/.",
		ExampleScenarios: "When internal/service/orders.go gains a new exported function PlaceOrder, this agent reads its body to understand what it does, writes orders_test.go with table tests covering valid input, invalid input, and error cases — using real assertions, not TODO stubs.",
		Detect: func(goMod string, moduleRoot string) bool {
			return goMod != ""
		},
		Build: func(deps registry.BuildDeps) registry.Runner {
			return New(Config{
				ID:         "test-agent",
				ModuleRoot: deps.ModuleRoot,
				Sender:     deps.Sender,
				FSBoard:    deps.FSBoard,
				Confirm:    deps.Confirm,
				Print:      deps.Print,
				Settle:     5 * time.Second,
			})
		},
	})
}
