// Package gogenerateagent is the conversational agent that keeps
// `//go:generate` output current. When .go files change, it wakes
// and hands the situation to Claude — Claude reads directives,
// decides which (if any) to run, and proposes the exec calls.
//
// The agent itself is just plumbing: subscribe to fsmonitor, debounce,
// wake. No decision logic in agent code. All "should this run? where?
// which directive?" judgment lives in Claude's head, guided by the
// role string and the project's actual state.
//
// Equilibrium: directives are up to date relative to their inputs,
// and `go build ./...` passes after generation.
package gogenerateagent

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/vinodhalaharvi/coven/agent"
	"github.com/vinodhalaharvi/coven/algebra/blackboard"
	"github.com/vinodhalaharvi/coven/fsmonitor"
	"github.com/vinodhalaharvi/coven/llm"
	"github.com/vinodhalaharvi/coven/registry"
)

// goGenerateDirective is the comment marker we want Claude to look for
// in source files. Stored as a constant so the literal "//go:generate"
// doesn't appear at column 1 of any line — Go's compiler treats
// "//go:..." at the start of a line as a build directive, which broke
// parsing of the role-string raw literal below.
const goGenerateDirective = "//" + "go:generate"

var Role = `You are the go-generate agent. Your job is to keep code generated by ` + goGenerateDirective + ` directives in sync with their source inputs, so the project compiles cleanly with up-to-date generated files.

You wake on any .go file change. Decide whether work is needed. If yes, propose it. If no, return a short "nothing to do" message and reach equilibrium.

Method:
  1. Find directives. Use search_text(pattern="` + goGenerateDirective + `", glob="**/*.go") to locate every directive across the project in one call. Don't read entire files; the directives are single-line comments and search_text returns each one with its line number.
  2. Decide what (if anything) needs running. Reason about which directives are stale relative to their source inputs based on what you observed in the wake observation. If nothing has changed in the inputs to any directive, there's nothing to do — say so and stop.
  3. Run targeted 'go generate' for the directories whose directives need execution, OR 'go generate ./...' if many directives across the project need re-running. You decide the right scope based on the situation. Each exec call is gated by user y/n.
  4. After generation, verify with 'go build ./...'.

Constraints:
  - You do NOT modify .go source files. The user controls what gets generated by writing directives in their source; you just execute the directives.
  - You do NOT touch directives that other agents own. Specifically: 'buf generate' (proto-agent's domain), 'sqlc generate' (sqlc-agent's domain), 'wire' (wire-agent's domain). If you see those tools in directives, leave them alone — those agents handle them.
  - You do NOT add deps to go.mod. If a directive needs a tool that isn't installed (e.g. mockgen, stringer), report that the user needs to install it.
  - Use search_text and pureast for navigation. Avoid read_file on whole files unless you specifically need to see the source around a directive (and even then, prefer line-range reads).

If there are no ` + goGenerateDirective + ` directives in the project, or all directives belong to other agents (buf/sqlc/wire), say so and stop. Equilibrium reached trivially.

When you've run the directives that needed running and the build is clean, summarize and stop. You'll wake again on the next .go file change.`

type Config struct {
	ID         string
	ModuleRoot string
	Sender     llm.Sender
	FSBoard    *blackboard.Board[fsmonitor.FileChangeFact]
	Confirm    agent.ConfirmFunc
	Print      agent.PrintFunc
	Settle     time.Duration
}

type Agent struct {
	cfg     Config
	inner   *agent.Agent
	mu      sync.Mutex
	pending bool
}

func New(cfg Config) *Agent {
	if cfg.ID == "" {
		cfg.ID = "gogenerate-agent"
	}
	if cfg.Settle <= 0 {
		// Long settle: gogenerate-agent is cross-cutting and should wake
		// AFTER the user has stopped editing and other agents have run.
		// 5s is a guess; tunable.
		cfg.Settle = 5 * time.Second
	}
	inner := agent.New(agent.Config{
		ID:       cfg.ID,
		Role:     Role,
		Tools:    agent.StandardTools(cfg.ModuleRoot),
		Sender:   cfg.Sender,
		Confirm:  cfg.Confirm,
		Print:    cfg.Print,
		MaxTurns: 40,
	})
	return &Agent{cfg: cfg, inner: inner}
}

// IsRelevant: any .go file change in the project. The agent doesn't
// pre-filter; Claude decides whether the change is interesting based
// on the directives it finds.
func IsRelevant(path string) bool {
	return strings.HasSuffix(path, ".go")
}

func (a *Agent) Run(ctx context.Context) error {
	go a.wakeOnce(ctx, "startup: just attached. Survey the project for //go:generate directives and bring the generated outputs to a healthy state. If there are no directives in your domain, say so and stop.")

	if a.cfg.FSBoard == nil {
		<-ctx.Done()
		return nil
	}

	sub := fsmonitor.Subscribe(a.cfg.FSBoard, func(f fsmonitor.FileChangeFact) bool {
		for _, p := range f.ChangedFiles {
			if IsRelevant(p) {
				return true
			}
		}
		return false
	})
	ch, err := sub(ctx)
	if err != nil {
		return err
	}

	var pendingFiles []string
	var timer *time.Timer
	resetTimer := func() {
		if timer != nil {
			timer.Stop()
		}
		timer = time.AfterFunc(a.cfg.Settle, func() {
			files := pendingFiles
			pendingFiles = nil
			a.wakeOnce(ctx, formatObservation(files))
		})
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case f, ok := <-ch:
			if !ok {
				return nil
			}
			for _, p := range f.ChangedFiles {
				if IsRelevant(p) {
					pendingFiles = append(pendingFiles, p)
				}
			}
			resetTimer()
		}
	}
}

func (a *Agent) wakeOnce(ctx context.Context, observation string) {
	a.mu.Lock()
	if a.pending {
		a.mu.Unlock()
		return
	}
	a.pending = true
	a.mu.Unlock()
	defer func() {
		a.mu.Lock()
		a.pending = false
		a.mu.Unlock()
	}()

	a.cfg.Print(fmt.Sprintf("\n  [%s] waking: %s\n", a.cfg.ID, truncate(observation, 80)))
	if _, err := a.inner.Wake(ctx, observation); err != nil {
		a.cfg.Print(fmt.Sprintf("  [%s] error: %v\n", a.cfg.ID, err))
	}
}

func (a *Agent) HistoryLen() int { return a.inner.HistoryLen() }

func formatObservation(files []string) string {
	if len(files) == 0 {
		return "filesystem activity in your domain (no specific files identified)."
	}
	seen := map[string]bool{}
	uniq := make([]string, 0, len(files))
	for _, f := range files {
		if !seen[f] {
			seen[f] = true
			uniq = append(uniq, f)
		}
	}
	// Show up to 10 changed files; beyond that, just count.
	const maxShown = 10
	if len(uniq) <= maxShown {
		if len(uniq) == 1 {
			return "observed change to: " + uniq[0]
		}
		return fmt.Sprintf("observed changes to %d files:\n  %s", len(uniq), strings.Join(uniq, "\n  "))
	}
	shown := uniq[:maxShown]
	rest := len(uniq) - maxShown
	return fmt.Sprintf("observed changes to %d files (showing first %d):\n  %s\n  ... and %d more", len(uniq), maxShown, strings.Join(shown, "\n  "), rest)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// init registers this agent. Detector: always relevant (any Go project
// could have go:generate directives, even if it doesn't currently).
// The agent itself reaches equilibrium trivially when there's nothing
// to do, so no harm in always-on.
func init() {
	registry.Register(registry.AgentSpec{
		Name:        "gogenerate",
		Description: "run //go:generate directives when their inputs change",
		Detect: func(goMod string, moduleRoot string) bool {
			// Always applicable. The role string handles the
			// "no directives, nothing to do" case cleanly.
			return goMod != ""
		},
		Build: func(deps registry.BuildDeps) registry.Runner {
			return New(Config{
				ID:         "gogenerate-agent",
				ModuleRoot: deps.ModuleRoot,
				Sender:     deps.Sender,
				FSBoard:    deps.FSBoard,
				Confirm:    deps.Confirm,
				Print:      deps.Print,
				Settle:     5 * time.Second,
			})
		},
	})
}
